
export const javaBaseCode = `LyogTmFtZSBvZiB0aGUgY2xhc3MgaGFzIHRvIGJlICJDb2RlYm94IiB0byBiZSBjb21waWxlZC4gRG8gbm90IGNoYW5nZSBpdC4gKi8KY2xhc3MgQ29kZWJveCB7CiAgICBwdWJsaWMgc3RhdGljIHZvaWQgbWFpbihTdHJpbmdbXSBhcmdzKSB7CiAgICAgICAgU3lzdGVtLm91dC5wcmludGxuKCJIZWxsbywgV29ybGQhIik7CiAgICB9Cn0=`

export const cppBaseCode = `I2luY2x1ZGUgPGlvc3RyZWFtPgppbnQgbWFpbigpIHsKICAgIC8vIFdyaXRlIEMrKyBjb2RlIGhlcmUKICAgIHN0ZDo6Y291dCA8PCAiSGVsbG8gd29ybGQhIjsKICAgIHJldHVybiAwOwp9`

export const pythonBaseCode = `I0NvZGUgSGVyZQpwcmludCgiSGVsbG8gd29ybGQiKQ==`